
USE benkonek;

SET @dummy_password = '$2y$10$RWPqcf2Gd.4s7DqWi1HkROYa6ZXOXr0HacQI5yfsXa7VFpa1D1Bj6';

INSERT INTO users (id, full_name, email, password_hash, role, is_active) VALUES
(101, 'USTU BINA SYAHDIBA', 'ustu.bina.syahdiba@student.benkonek.test', @dummy_password, 'musician', 1),
(102, 'TUTI PURWANINGSIH', 'tuti.purwaningsih@student.benkonek.test', @dummy_password, 'musician', 1),
(103, 'SYAHRI BANUN', 'syahri.banun@student.benkonek.test', @dummy_password, 'musician', 1),
(104, 'MUHAMMAD ADITYA NUGRAHA', 'muhammad.aditya.nugraha@student.benkonek.test', @dummy_password, 'musician', 1),
(105, 'FA`IZ AKBAR HIZBULLAH', 'faiz.akbar.hizbullah@student.benkonek.test', @dummy_password, 'musician', 1),
(106, 'MUHAMMAD HISYAM AL ARBY', 'muhammad.hisyam.al.arby@student.benkonek.test', @dummy_password, 'musician', 1),
(107, 'MUHAMMAD FATIH AL FAWWAZ', 'muhammad.fatih.al.fawwaz@student.benkonek.test', @dummy_password, 'musician', 1),
(108, 'ARDHIAN JUNIOR CAESAR', 'ardhian.junior.caesar@student.benkonek.test', @dummy_password, 'musician', 1),
(109, 'SHABRINA SARAYATI', 'shabrina.sarayati@student.benkonek.test', @dummy_password, 'musician', 1),
(110, 'CHELSEA', 'chelsea@student.benkonek.test', @dummy_password, 'musician', 1),
(111, 'BELVANY VIRGINIA KENETTA SETIAWAN', 'belvany.virginia.kenetta@student.benkonek.test', @dummy_password, 'musician', 1),
(112, 'JEREMY MATTATHIAS MBOE', 'jeremy.mattathias.mboe@student.benkonek.test', @dummy_password, 'musician', 1),
(113, 'SULTAN HAMDI JAILANI DAULAY', 'sultan.hamdi.jailani@student.benkonek.test', @dummy_password, 'musician', 1),
(114, 'JONATHAN ANDERSON MANURUNG', 'jonathan.anderson.manurung@student.benkonek.test', @dummy_password, 'musician', 1),
(115, 'UMAR AL FARIS', 'umar.al.faris@student.benkonek.test', @dummy_password, 'musician', 1),
(116, 'MUHAMMAD HADIDAN NURHAUNAN', 'muhammad.hadidan.nurhaunan@student.benkonek.test', @dummy_password, 'musician', 1),
(117, 'TRI ISMUNHADI JULIK CAKRA WIBAWA', 'tri.ismunhadi.julik@student.benkonek.test', @dummy_password, 'musician', 1),
(118, 'MUHAMMAD FARHAN', 'muhammad.farhan@student.benkonek.test', @dummy_password, 'musician', 1),
(119, 'FERRI ADI PRASETYA', 'ferri.adi.prasetya@student.benkonek.test', @dummy_password, 'musician', 1),
(120, 'FAZLE MAWLA WAHYUHANDA', 'fazle.mawla.wahyuhanda@student.benkonek.test', @dummy_password, 'musician', 1),
(121, 'IZZAH NAUFALIA ADILA', 'izzah.naufalia.adila@student.benkonek.test', @dummy_password, 'musician', 1),
(122, 'ROYAN HARITS YUSTANTO', 'royan.harits.yustanto@student.benkonek.test', @dummy_password, 'musician', 1),
(123, 'BERLIANA SARLITA RAHAJENG', 'berliana.sarlita.rahajeng@student.benkonek.test', @dummy_password, 'musician', 1),
(124, 'MOCHAMMAD HENRY ALIFIAN', 'mochammad.henry.alifian@student.benkonek.test', @dummy_password, 'musician', 1),
(125, 'RAFLI DJANUAR ANANGSYAH', 'rafli.djanuar.anangsyah@student.benkonek.test', @dummy_password, 'musician', 1),
(126, 'ARYA PRATAMA RHAMA PUTRA', 'arya.pratama.rhama@student.benkonek.test', @dummy_password, 'musician', 1),
(127, 'RADITYA AKMAL', 'raditya.akmal@student.benkonek.test', @dummy_password, 'musician', 1),
(128, 'KAYLA RIZA PUTRI IRJAYANTO', 'kayla.riza.putri@student.benkonek.test', @dummy_password, 'musician', 1),
(129, 'WAYAN RADITYA PUTRA', 'wayan.raditya.putra@student.benkonek.test', @dummy_password, 'musician', 1),
(130, 'MUHAMMAD ROBITUL JAKSY', 'muhammad.robitul.jaksy@student.benkonek.test', @dummy_password, 'musician', 1),
(131, 'JYLAN ANNISA MUMTAZA SYIDANA', 'jylan.annisa.mumtaza@student.benkonek.test', @dummy_password, 'musician', 1),
(132, 'SEIFELDEIN AKBAR', 'seifeldein.akbar@student.benkonek.test', @dummy_password, 'musician', 1),
(133, 'MUHAMMAD NABIL DHIYAULHAQ', 'muhammad.nabil.dhiyaulhaq@student.benkonek.test', @dummy_password, 'musician', 1),
(134, 'RASYA AUDREA BRAMANTYA WIJAYA', 'rasya.audrea.bramantya@student.benkonek.test', @dummy_password, 'musician', 1),
(135, 'NAZHIF BERLIAN NASHRULLAH', 'nazhif.berlian.nashrullah@student.benkonek.test', @dummy_password, 'musician', 1),
(136, 'MUHAMMAD DAYYAN GHAZANFAR LATIEF', 'muhammad.dayyan.ghazanfar@student.benkonek.test', @dummy_password, 'musician', 1),
(137, 'GHIFFARY ABDUL HAKIM', 'ghiffary.abdul.hakim@student.benkonek.test', @dummy_password, 'musician', 1),
(138, 'AHMAD NAUFAL FARRAS', 'ahmad.naufal.farras@student.benkonek.test', @dummy_password, 'musician', 1),
(139, 'KEVIN NICHOLAS NATHANAEL', 'kevin.nicholas.nathanael@student.benkonek.test', @dummy_password, 'musician', 1),
(140, 'SYAUQI NABIL TASRI', 'syauqi.nabil.tasri@student.benkonek.test', @dummy_password, 'musician', 1),
(141, 'SITTI AMINAH', 'sitti.aminah@student.benkonek.test', @dummy_password, 'musician', 1),
(142, 'INDRA PRASETYA MAHESWARA', 'indra.prasetya.maheswara@student.benkonek.test', @dummy_password, 'musician', 1),
(143, 'MUHAMMAD FATHUR AZIZ', 'muhammad.fathur.aziz@student.benkonek.test', @dummy_password, 'musician', 1),
(144, 'WIJDAN RAZEFI AL HAWWARI', 'wijdan.razefi.al.hawwari@student.benkonek.test', @dummy_password, 'musician', 1),
(145, 'MOHAMMAD AKMAL FAYYAZI', 'mohammad.akmal.fayyazi@student.benkonek.test', @dummy_password, 'musician', 1),
(146, 'ARVITO RAJAPANDYA NATLYSANDRO', 'arvito.rajapandya@student.benkonek.test', @dummy_password, 'musician', 1),
(147, 'MARVEL MAHANARA', 'marvel.mahanara@student.benkonek.test', @dummy_password, 'musician', 1)
ON DUPLICATE KEY UPDATE
full_name = VALUES(full_name),
email = VALUES(email),
password_hash = VALUES(password_hash),
role = VALUES(role),
is_active = VALUES(is_active);

INSERT INTO musicians (user_id, full_name, primary_instrument, experience_level, location_city, bio, whatsapp_number, portfolio_url) VALUES
(101, 'USTU BINA SYAHDIBA', 'Vokal', 'Intermediate', 'Jakarta', 'Vokalis pop alternatif yang nyaman untuk akustik dan band format penuh.', '08123000101', 'https://instagram.com/ustu.benkonek'),
(102, 'TUTI PURWANINGSIH', 'Keyboard', 'Beginner', 'Bandung', 'Suka progresi chord city pop dan sedang belajar synth pad untuk live session.', '08123000102', ''),
(103, 'SYAHRI BANUN', 'Bass', 'Intermediate', 'Yogyakarta', 'Pemain bass yang rapi menjaga groove untuk pop, funk, dan indie.', '08123000103', ''),
(104, 'MUHAMMAD ADITYA NUGRAHA', 'Drum', 'Advanced', 'Surabaya', 'Drummer dengan stamina gig reguler dan klik metronom yang stabil.', '08123000104', ''),
(105, 'FA`IZ AKBAR HIZBULLAH', 'Gitar', 'Intermediate', 'Malang', 'Gitaris rhythm dengan selera efek chorus, delay, dan drive tipis.', '08123000105', ''),
(106, 'MUHAMMAD HISYAM AL ARBY', 'Saxophone', 'Intermediate', 'Jakarta', 'Sax player untuk pop, jazz ringan, dan brass section sederhana.', '08123000106', ''),
(107, 'MUHAMMAD FATIH AL FAWWAZ', 'Gitar', 'Beginner', 'Depok', 'Belajar lead gitar dan tertarik masuk project indie kampus.', '08123000107', ''),
(108, 'ARDHIAN JUNIOR CAESAR', 'Drum', 'Intermediate', 'Bekasi', 'Drummer rock alternatif yang bisa latihan rutin akhir pekan.', '08123000108', ''),
(109, 'SHABRINA SARAYATI', 'Vokal', 'Advanced', 'Tangerang', 'Vokalis alto, bisa backing vocal, harmonisasi, dan menulis lirik.', '08123000109', ''),
(110, 'CHELSEA', 'Keyboard', 'Intermediate', 'Jakarta', 'Keyboardist untuk pop, worship, dan R&B sederhana.', '08123000110', ''),
(111, 'BELVANY VIRGINIA KENETTA SETIAWAN', 'Violin', 'Advanced', 'Bandung', 'Violinist untuk folk, pop orchestra, dan rekaman string layer.', '08123000111', ''),
(112, 'JEREMY MATTATHIAS MBOE', 'Bass', 'Professional', 'Jakarta', 'Bassist session yang nyaman main dengan chart dan click track.', '08123000112', ''),
(113, 'SULTAN HAMDI JAILANI DAULAY', 'Drum', 'Intermediate', 'Medan', 'Drummer pop punk dan alternative rock dengan pukulan solid.', '08123000113', ''),
(114, 'JONATHAN ANDERSON MANURUNG', 'Gitar', 'Advanced', 'Medan', 'Lead guitarist dengan influence blues rock dan modern worship.', '08123000114', ''),
(115, 'UMAR AL FARIS', 'Bass', 'Beginner', 'Bogor', 'Bassist pemula yang siap latihan rutin dan belajar lagu setlist.', '08123000115', ''),
(116, 'MUHAMMAD HADIDAN NURHAUNAN', 'Vokal', 'Intermediate', 'Semarang', 'Vokalis tenor untuk pop, alternative, dan acoustic night.', '08123000116', ''),
(117, 'TRI ISMUNHADI JULIK CAKRA WIBAWA', 'Gitar', 'Professional', 'Surakarta', 'Gitaris session dengan pengalaman panggung wedding dan event.', '08123000117', ''),
(118, 'MUHAMMAD FARHAN', 'Keyboard', 'Advanced', 'Jakarta', 'Keyboardist yang bisa pad, piano, organ, dan sequencing sederhana.', '08123000118', ''),
(119, 'FERRI ADI PRASETYA', 'Drum', 'Intermediate', 'Surabaya', 'Drummer dengan style punk, rock, dan indie garage.', '08123000119', ''),
(120, 'FAZLE MAWLA WAHYUHANDA', 'Gitar', 'Advanced', 'Bandung', 'Gitaris ambient dan post-rock, suka delay panjang dan tremolo picking.', '08123000120', ''),
(121, 'IZZAH NAUFALIA ADILA', 'Vokal', 'Intermediate', 'Yogyakarta', 'Vokalis pop folk dengan tone lembut dan kemampuan harmonisasi.', '08123000121', ''),
(122, 'ROYAN HARITS YUSTANTO', 'Bass', 'Intermediate', 'Malang', 'Bassist alternative dan indie rock, siap latihan malam.', '08123000122', ''),
(123, 'BERLIANA SARLITA RAHAJENG', 'Keyboard', 'Beginner', 'Semarang', 'Keyboardist pemula untuk project pop dan cover akustik.', '08123000123', ''),
(124, 'MOCHAMMAD HENRY ALIFIAN', 'Drum', 'Advanced', 'Jakarta', 'Drummer fusion-pop yang suka groove rapat dan ghost note.', '08123000124', ''),
(125, 'RAFLI DJANUAR ANANGSYAH', 'Gitar', 'Intermediate', 'Bogor', 'Gitaris rhythm untuk indie pop, britpop, dan alternative.', '08123000125', ''),
(126, 'ARYA PRATAMA RHAMA PUTRA', 'Bass', 'Advanced', 'Tangerang', 'Bassist dengan tone tebal, nyaman main pick maupun fingerstyle.', '08123000126', ''),
(127, 'RADITYA AKMAL', 'Vokal', 'Beginner', 'Depok', 'Vokalis pemula yang mencari band latihan reguler.', '08123000127', ''),
(128, 'KAYLA RIZA PUTRI IRJAYANTO', 'Piano', 'Intermediate', 'Jakarta', 'Pianist pop ballad dan acoustic session.', '08123000128', ''),
(129, 'WAYAN RADITYA PUTRA', 'Gitar', 'Advanced', 'Denpasar', 'Gitaris rock dan funk dengan pengalaman event kampus.', '08123000129', ''),
(130, 'MUHAMMAD ROBITUL JAKSY', 'Drum', 'Beginner', 'Bekasi', 'Drummer pemula yang fokus basic groove dan tempo.', '08123000130', ''),
(131, 'JYLAN ANNISA MUMTAZA SYIDANA', 'Vokal', 'Advanced', 'Bandung', 'Vokalis pop R&B dengan range luas dan stage presence kuat.', '08123000131', ''),
(132, 'SEIFELDEIN AKBAR', 'Bass', 'Intermediate', 'Jakarta', 'Bassist yang suka neo soul, funk, dan city pop.', '08123000132', ''),
(133, 'MUHAMMAD NABIL DHIYAULHAQ', 'Gitar', 'Intermediate', 'Surabaya', 'Gitaris indie rock yang siap untuk rekaman demo.', '08123000133', ''),
(134, 'RASYA AUDREA BRAMANTYA WIJAYA', 'Keyboard', 'Advanced', 'Yogyakarta', 'Keyboardist synth-pop dan electronic pop, bisa arrange layer.', '08123000134', ''),
(135, 'NAZHIF BERLIAN NASHRULLAH', 'Drum', 'Professional', 'Jakarta', 'Drummer session untuk recording dan live click track.', '08123000135', ''),
(136, 'MUHAMMAD DAYYAN GHAZANFAR LATIEF', 'Gitar', 'Beginner', 'Bogor', 'Gitaris pemula yang tertarik shoegaze dan alternative.', '08123000136', ''),
(137, 'GHIFFARY ABDUL HAKIM', 'Bass', 'Intermediate', 'Malang', 'Bassist rock yang suka tone fuzz dan chorus.', '08123000137', ''),
(138, 'AHMAD NAUFAL FARRAS', 'Vokal', 'Intermediate', 'Jakarta', 'Vokalis pop punk dan alternative, bisa growl ringan.', '08123000138', ''),
(139, 'KEVIN NICHOLAS NATHANAEL', 'Gitar', 'Advanced', 'Tangerang', 'Lead guitarist blues, pop rock, dan session event.', '08123000139', ''),
(140, 'SYAUQI NABIL TASRI', 'Drum', 'Intermediate', 'Bandung', 'Drummer indie pop dengan feel ringan dan dinamis.', '08123000140', ''),
(141, 'SITTI AMINAH', 'Vokal', 'Beginner', 'Makassar', 'Vokalis pemula yang ingin berkembang lewat project akustik.', '08123000141', ''),
(142, 'INDRA PRASETYA MAHESWARA', 'Keyboard', 'Professional', 'Jakarta', 'Keyboardist session dengan setup MainStage dan sound library lengkap.', '08123000142', ''),
(143, 'MUHAMMAD FATHUR AZIZ', 'Bass', 'Advanced', 'Surabaya', 'Bassist funk rock dengan pengalaman panggung festival sekolah.', '08123000143', ''),
(144, 'WIJDAN RAZEFI AL HAWWARI', 'Gitar', 'Intermediate', 'Semarang', 'Gitaris alternative pop yang suka aransemen clean dan jangly.', '08123000144', ''),
(145, 'MOHAMMAD AKMAL FAYYAZI', 'Drum', 'Advanced', 'Depok', 'Drummer rock modern dengan double pedal dasar.', '08123000145', ''),
(146, 'ARVITO RAJAPANDYA NATLYSANDRO', 'Saxophone', 'Beginner', 'Bandung', 'Pemain sax pemula untuk jazz pop dan ensemble kecil.', '08123000146', ''),
(147, 'MARVEL MAHANARA', 'Gitar', 'Professional', 'Jakarta', 'Gitaris session untuk pop, R&B, dan live corporate event.', '08123000147', '')
ON DUPLICATE KEY UPDATE
full_name = VALUES(full_name),
primary_instrument = VALUES(primary_instrument),
experience_level = VALUES(experience_level),
location_city = VALUES(location_city),
bio = VALUES(bio),
whatsapp_number = VALUES(whatsapp_number),
portfolio_url = VALUES(portfolio_url);

INSERT INTO users (id, full_name, email, password_hash, role, is_active) VALUES
(201, 'Modjoermakmoer', 'modjoermakmoer@band.benkonek.test', @dummy_password, 'band', 1),
(202, 'Distorsi Halus', 'distorsi.halus@band.benkonek.test', @dummy_password, 'band', 1),
(203, 'Ruang Reverb', 'ruang.reverb@band.benkonek.test', @dummy_password, 'band', 1),
(204, 'Orkes Kawat', 'orkes.kawat@band.benkonek.test', @dummy_password, 'band', 1),
(205, 'Nada Garasi', 'nada.garasi@band.benkonek.test', @dummy_password, 'band', 1),
(206, 'Terminal Chorus', 'terminal.chorus@band.benkonek.test', @dummy_password, 'band', 1),
(207, 'Lautan Fuzz', 'lautan.fuzz@band.benkonek.test', @dummy_password, 'band', 1),
(208, 'Pita Magnetik', 'pita.magnetik@band.benkonek.test', @dummy_password, 'band', 1),
(209, 'Sirkuit Melodi', 'sirkuit.melodi@band.benkonek.test', @dummy_password, 'band', 1),
(210, 'Afterclass Riot', 'afterclass.riot@band.benkonek.test', @dummy_password, 'band', 1)
ON DUPLICATE KEY UPDATE
full_name = VALUES(full_name),
email = VALUES(email),
password_hash = VALUES(password_hash),
role = VALUES(role),
is_active = VALUES(is_active);

INSERT INTO bands (id, user_id, band_name, formation_year, main_genre, basecamp_location, bio, whatsapp_number) VALUES
(1, 201, 'Modjoermakmoer', 2021, 'Indie Pop', 'Jakarta Selatan', 'Band pop sore-sore dengan chorus hangat dan aransemen gitar jangly.', '08224000201'),
(2, 202, 'Distorsi Halus', 2022, 'Alternative Rock', 'Bandung', 'Alternative rock dengan fuzz manis, vokal melodis, dan setlist energik.', '08224000202'),
(3, 203, 'Ruang Reverb', 2020, 'Dream Pop', 'Yogyakarta', 'Unit dream pop yang banyak memakai reverb, chorus, dan synth pad.', '08224000203'),
(4, 204, 'Orkes Kawat', 2019, 'Folk Pop', 'Semarang', 'Folk pop akustik dengan sentuhan violin dan perkusi ringan.', '08224000204'),
(5, 205, 'Nada Garasi', 2023, 'Garage Rock', 'Surabaya', 'Garage rock lugas, latihan cepat, dan siap manggung di skena kampus.', '08224000205'),
(6, 206, 'Terminal Chorus', 2024, 'City Pop', 'Tangerang', 'City pop modern dengan bass groovy, electric piano, dan hook cerah.', '08224000206'),
(7, 207, 'Lautan Fuzz', 2018, 'Stoner Rock', 'Malang', 'Riff berat, tempo santai, dan ampli fuzz yang jadi identitas utama.', '08224000207'),
(8, 208, 'Pita Magnetik', 2021, 'Synth Pop', 'Depok', 'Synth pop retro dengan drum machine, bass analog, dan vokal dreamy.', '08224000208'),
(9, 209, 'Sirkuit Melodi', 2022, 'Pop Punk', 'Bekasi', 'Pop punk cepat dan sing-along, cocok untuk gig sekolah dan kampus.', '08224000209'),
(10, 210, 'Afterclass Riot', 2024, 'Punk Rock', 'Bogor', 'Band punk rock after-school dengan energi mentah dan lagu singkat.', '08224000210')
ON DUPLICATE KEY UPDATE
band_name = VALUES(band_name),
formation_year = VALUES(formation_year),
main_genre = VALUES(main_genre),
basecamp_location = VALUES(basecamp_location),
bio = VALUES(bio),
whatsapp_number = VALUES(whatsapp_number);

INSERT INTO vacancies (band_id, title, project_type, needed_instrument, description, status) VALUES
(1, 'Cari Keyboardist untuk Single Baru', 'Recording', 'Keyboard', 'Butuh keyboardist yang bisa isi pad, piano, dan sedikit synth lead untuk satu single indie pop.', 'Open'),
(1, 'Bassist Tetap untuk Gig Bulanan', 'Permanent', 'Bass', 'Modjoermakmoer butuh bassist tetap yang bisa latihan malam dan siap gig sebulan dua kali.', 'Open'),
(2, 'Drummer Rock Alternatif', 'Permanent', 'Drum', 'Distorsi Halus mencari drummer dengan pukulan solid dan bisa main pakai click.', 'Open'),
(2, 'Lead Guitar Session', 'Session', 'Gitar', 'Butuh gitaris lead untuk isi solo dan ambience di dua lagu demo.', 'Closed'),
(3, 'Vokalis Dream Pop', 'Permanent', 'Vokal', 'Ruang Reverb mencari vokalis dengan karakter lembut dan suka eksplorasi lirik dreamy.', 'Open'),
(3, 'Synth Player Live', 'Gig', 'Keyboard', 'Dibutuhkan synth player untuk live set 30 menit di acara kampus.', 'Open'),
(4, 'Violin Player untuk Folk Set', 'Session', 'Violin', 'Orkes Kawat butuh violin player untuk menambah warna di tiga lagu folk pop.', 'Open'),
(4, 'Perkusi Cajon', 'Gig', 'Perkusi', 'Butuh pemain cajon untuk acoustic night akhir pekan.', 'Open'),
(5, 'Vokalis Garage Rock', 'Permanent', 'Vokal', 'Nada Garasi mencari vokalis yang percaya diri, tidak takut panggung kecil, dan suka musik cepat.', 'Open'),
(6, 'Bassist Groovy City Pop', 'Permanent', 'Bass', 'Terminal Chorus butuh bassist dengan feel funk dan groove rapat.', 'Open'),
(6, 'Saxophone untuk Intro Lagu', 'Recording', 'Saxophone', 'Sesi rekaman singkat untuk intro dan bridge single city pop.', 'Open'),
(7, 'Drummer Stoner Rock', 'Permanent', 'Drum', 'Lautan Fuzz mencari drummer yang stabil main tempo lambat dan riff berat.', 'Open'),
(8, 'Vokalis Synth Pop', 'Permanent', 'Vokal', 'Pita Magnetik mencari vokalis yang nyaman dengan backing track dan synth pop retro.', 'Open'),
(9, 'Gitaris Rhythm Pop Punk', 'Permanent', 'Gitar', 'Sirkuit Melodi butuh gitaris rhythm untuk power chord cepat dan backing vocal.', 'Open'),
(10, 'Bassist Punk Rock', 'Permanent', 'Bass', 'Afterclass Riot mencari bassist yang bisa latihan setelah jam sekolah/kuliah.', 'Open');
